server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dbIndexingTest
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.format_sql]': true

  output:
    ansi:
      enabled: always

logging:
  level:
    '[org.springframework.boot.web]': DEBUG
    org:
      springframework:
        cache: DEBUG
